# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testIM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sixLive
#  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8'

  pod 'RongCloudIM/IMLib', '~> 2.8.3'
  pod 'RongCloudIM/IMKit', '~> 2.8.3'  

  target 'testIMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testIMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
